### ISSUE TITLE
files to delete

### ISSUE THREAD

**Issue by Karyum** [WebAhead5/short_is_best#2]
[Coments.model.js](https://github.com/WebAhead5/short_is_best/blob/master/src/models/comments/Coments.model.js)

**Comment by Karyum** [comment]
also [test.js](https://github.com/WebAhead5/short_is_best/blob/master/database/test.js) should not be in the database folder, it should be in a separate folder

**Comment by fridabu** [comment]
the comments file was removed, the test file moved
